name: First App System

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - my_own_network
  db:
    image: mongo:latest
    networks:
      - my_own_network

networks:
  my_own_network:
    driver: bridge